services:
  bot:
    build: .
    container_name: comp7940-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb+srv://Gino:1234@chatbot.nejdxh9.mongodb.net/
      MONGO_DB_NAME: chatbot_db
      MONGO_COLLECTION_NAME: users
    volumes:
      - ./config.ini:/comp7940-lab/config.ini:ro

  mongodb:
    image: mongo:7
    container_name: comp7940-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: comp7940
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: